name: Terraform State Cleanup & Apply

on:
  push:
    branches:
      - main  # Adjust to your target branch

env:
  WORKING_DIR: "."

jobs:
  terraform-state-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      # - name: Remove KMS Key from Terraform State
      #   run: terraform state rm aws_kms_key.my_key
      #   working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.WORKING_DIR }}
